### ISSUE TITLE
Adding stats

### ISSUE THREAD

**Issue by genghistong** [howardjing/BundledGoods#3]
1. Finding median "average time between statement clicks", only looking at users above that median. = "good performers"
2. Finding median average time spent per question for all users, only looking at users above that median. = "good performers pt. 2"
3. (less important) not choosing combo when it is optimal.

**Comment by howardjing** [comment]
1f67b2cc021ea2ab1ac8db008216ad86078fd60a  adding machinery to find users with above median score implements 1 and 2

**Comment by howardjing** [comment]
5d50584df9d21396405c26e25695cf1d626d7d90 not choosing combo when should implements 3
